/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapsIndexRouteImport } from './routes/roadmaps.index'
import { Route as RoadmapsRoadmapIdRouteImport } from './routes/roadmaps.$roadmapId'
import { Route as RoadmapsNewRouteImport } from './routes/roadmaps.new'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as ApiPublicV1StatsRouteImport } from './routes/api/public/v1/stats'
import { Route as ApiPublicV1RoadmapsIndexRouteImport } from './routes/api/public/v1/roadmaps/index'
import { Route as ApiPublicV1RoadmapsRoadmapIdIndexRouteImport } from './routes/api/public/v1/roadmaps/$roadmapId/index'
import { Route as ApiPublicV1RoadmapsRoadmapIdItemsRouteImport } from './routes/api/public/v1/roadmaps/$roadmapId/items'
import { Route as ApiPublicV1RoadmapsRoadmapIdCapacityIndexRouteImport } from './routes/api/public/v1/roadmaps/$roadmapId/capacity/index'
import { Route as ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRouteImport } from './routes/api/public/v1/roadmaps/$roadmapId/capacity/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsIndexRoute = RoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoadmapIdRoute = RoadmapsRoadmapIdRouteImport.update({
  id: '/roadmaps/$roadmapId',
  path: '/roadmaps/$roadmapId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsNewRoute = RoadmapsNewRouteImport.update({
  id: '/roadmaps/new',
  path: '/roadmaps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiPublicV1StatsRoute = ApiPublicV1StatsRouteImport.update({
  id: '/api/public/v1/stats',
  path: '/api/public/v1/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RoadmapsIndexRoute =
  ApiPublicV1RoadmapsIndexRouteImport.update({
    id: '/api/public/v1/roadmaps/',
    path: '/api/public/v1/roadmaps/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1RoadmapsRoadmapIdIndexRoute =
  ApiPublicV1RoadmapsRoadmapIdIndexRouteImport.update({
    id: '/api/public/v1/roadmaps/$roadmapId/',
    path: '/api/public/v1/roadmaps/$roadmapId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1RoadmapsRoadmapIdItemsRoute =
  ApiPublicV1RoadmapsRoadmapIdItemsRouteImport.update({
    id: '/api/public/v1/roadmaps/$roadmapId/items',
    path: '/api/public/v1/roadmaps/$roadmapId/items',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute =
  ApiPublicV1RoadmapsRoadmapIdCapacityIndexRouteImport.update({
    id: '/api/public/v1/roadmaps/$roadmapId/capacity/',
    path: '/api/public/v1/roadmaps/$roadmapId/capacity/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute =
  ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRouteImport.update({
    id: '/api/public/v1/roadmaps/$roadmapId/capacity/history',
    path: '/api/public/v1/roadmaps/$roadmapId/capacity/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/roadmaps/': typeof ApiPublicV1RoadmapsIndexRoute
  '/api/public/v1/roadmaps/$roadmapId/items': typeof ApiPublicV1RoadmapsRoadmapIdItemsRoute
  '/api/public/v1/roadmaps/$roadmapId/': typeof ApiPublicV1RoadmapsRoadmapIdIndexRoute
  '/api/public/v1/roadmaps/$roadmapId/capacity/history': typeof ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute
  '/api/public/v1/roadmaps/$roadmapId/capacity/': typeof ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/roadmaps': typeof RoadmapsIndexRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/roadmaps': typeof ApiPublicV1RoadmapsIndexRoute
  '/api/public/v1/roadmaps/$roadmapId/items': typeof ApiPublicV1RoadmapsRoadmapIdItemsRoute
  '/api/public/v1/roadmaps/$roadmapId': typeof ApiPublicV1RoadmapsRoadmapIdIndexRoute
  '/api/public/v1/roadmaps/$roadmapId/capacity/history': typeof ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute
  '/api/public/v1/roadmaps/$roadmapId/capacity': typeof ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/roadmaps/': typeof ApiPublicV1RoadmapsIndexRoute
  '/api/public/v1/roadmaps/$roadmapId/items': typeof ApiPublicV1RoadmapsRoadmapIdItemsRoute
  '/api/public/v1/roadmaps/$roadmapId/': typeof ApiPublicV1RoadmapsRoadmapIdIndexRoute
  '/api/public/v1/roadmaps/$roadmapId/capacity/history': typeof ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute
  '/api/public/v1/roadmaps/$roadmapId/capacity/': typeof ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/settings'
    | '/roadmaps/$roadmapId'
    | '/roadmaps/new'
    | '/settings/billing'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/users'
    | '/roadmaps/'
    | '/api/public/v1/stats'
    | '/api/public/v1/roadmaps/'
    | '/api/public/v1/roadmaps/$roadmapId/items'
    | '/api/public/v1/roadmaps/$roadmapId/'
    | '/api/public/v1/roadmaps/$roadmapId/capacity/history'
    | '/api/public/v1/roadmaps/$roadmapId/capacity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/settings'
    | '/roadmaps/$roadmapId'
    | '/roadmaps/new'
    | '/settings/billing'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/users'
    | '/roadmaps'
    | '/api/public/v1/stats'
    | '/api/public/v1/roadmaps'
    | '/api/public/v1/roadmaps/$roadmapId/items'
    | '/api/public/v1/roadmaps/$roadmapId'
    | '/api/public/v1/roadmaps/$roadmapId/capacity/history'
    | '/api/public/v1/roadmaps/$roadmapId/capacity'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/settings'
    | '/roadmaps/$roadmapId'
    | '/roadmaps/new'
    | '/settings/billing'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/users'
    | '/roadmaps/'
    | '/api/public/v1/stats'
    | '/api/public/v1/roadmaps/'
    | '/api/public/v1/roadmaps/$roadmapId/items'
    | '/api/public/v1/roadmaps/$roadmapId/'
    | '/api/public/v1/roadmaps/$roadmapId/capacity/history'
    | '/api/public/v1/roadmaps/$roadmapId/capacity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  RoadmapsRoadmapIdRoute: typeof RoadmapsRoadmapIdRoute
  RoadmapsNewRoute: typeof RoadmapsNewRoute
  RoadmapsIndexRoute: typeof RoadmapsIndexRoute
  ApiPublicV1StatsRoute: typeof ApiPublicV1StatsRoute
  ApiPublicV1RoadmapsIndexRoute: typeof ApiPublicV1RoadmapsIndexRoute
  ApiPublicV1RoadmapsRoadmapIdItemsRoute: typeof ApiPublicV1RoadmapsRoadmapIdItemsRoute
  ApiPublicV1RoadmapsRoadmapIdIndexRoute: typeof ApiPublicV1RoadmapsRoadmapIdIndexRoute
  ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute: typeof ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute
  ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute: typeof ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/': {
      id: '/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof RoadmapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/$roadmapId': {
      id: '/roadmaps/$roadmapId'
      path: '/roadmaps/$roadmapId'
      fullPath: '/roadmaps/$roadmapId'
      preLoaderRoute: typeof RoadmapsRoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/new': {
      id: '/roadmaps/new'
      path: '/roadmaps/new'
      fullPath: '/roadmaps/new'
      preLoaderRoute: typeof RoadmapsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/public/v1/stats': {
      id: '/api/public/v1/stats'
      path: '/api/public/v1/stats'
      fullPath: '/api/public/v1/stats'
      preLoaderRoute: typeof ApiPublicV1StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/roadmaps/': {
      id: '/api/public/v1/roadmaps/'
      path: '/api/public/v1/roadmaps'
      fullPath: '/api/public/v1/roadmaps/'
      preLoaderRoute: typeof ApiPublicV1RoadmapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/roadmaps/$roadmapId/': {
      id: '/api/public/v1/roadmaps/$roadmapId/'
      path: '/api/public/v1/roadmaps/$roadmapId'
      fullPath: '/api/public/v1/roadmaps/$roadmapId/'
      preLoaderRoute: typeof ApiPublicV1RoadmapsRoadmapIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/roadmaps/$roadmapId/items': {
      id: '/api/public/v1/roadmaps/$roadmapId/items'
      path: '/api/public/v1/roadmaps/$roadmapId/items'
      fullPath: '/api/public/v1/roadmaps/$roadmapId/items'
      preLoaderRoute: typeof ApiPublicV1RoadmapsRoadmapIdItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/roadmaps/$roadmapId/capacity/': {
      id: '/api/public/v1/roadmaps/$roadmapId/capacity/'
      path: '/api/public/v1/roadmaps/$roadmapId/capacity'
      fullPath: '/api/public/v1/roadmaps/$roadmapId/capacity/'
      preLoaderRoute: typeof ApiPublicV1RoadmapsRoadmapIdCapacityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/roadmaps/$roadmapId/capacity/history': {
      id: '/api/public/v1/roadmaps/$roadmapId/capacity/history'
      path: '/api/public/v1/roadmaps/$roadmapId/capacity/history'
      fullPath: '/api/public/v1/roadmaps/$roadmapId/capacity/history'
      preLoaderRoute: typeof ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  RoadmapsRoadmapIdRoute: RoadmapsRoadmapIdRoute,
  RoadmapsNewRoute: RoadmapsNewRoute,
  RoadmapsIndexRoute: RoadmapsIndexRoute,
  ApiPublicV1StatsRoute: ApiPublicV1StatsRoute,
  ApiPublicV1RoadmapsIndexRoute: ApiPublicV1RoadmapsIndexRoute,
  ApiPublicV1RoadmapsRoadmapIdItemsRoute:
    ApiPublicV1RoadmapsRoadmapIdItemsRoute,
  ApiPublicV1RoadmapsRoadmapIdIndexRoute:
    ApiPublicV1RoadmapsRoadmapIdIndexRoute,
  ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute:
    ApiPublicV1RoadmapsRoadmapIdCapacityHistoryRoute,
  ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute:
    ApiPublicV1RoadmapsRoadmapIdCapacityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
