/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapsIndexRouteImport } from './routes/roadmaps.index'
import { Route as RoadmapsRoadmapIdRouteImport } from './routes/roadmaps.$roadmapId'
import { Route as RoadmapsNewRouteImport } from './routes/roadmaps.new'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsIndexRoute = RoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoadmapIdRoute = RoadmapsRoadmapIdRouteImport.update({
  id: '/roadmaps/$roadmapId',
  path: '/roadmaps/$roadmapId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsNewRoute = RoadmapsNewRouteImport.update({
  id: '/roadmaps/new',
  path: '/roadmaps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/roadmaps': typeof RoadmapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/settings'
    | '/roadmaps/$roadmapId'
    | '/roadmaps/new'
    | '/settings/billing'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/users'
    | '/roadmaps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/settings'
    | '/roadmaps/$roadmapId'
    | '/roadmaps/new'
    | '/settings/billing'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/users'
    | '/roadmaps'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/settings'
    | '/roadmaps/$roadmapId'
    | '/roadmaps/new'
    | '/settings/billing'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/users'
    | '/roadmaps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  RoadmapsRoadmapIdRoute: typeof RoadmapsRoadmapIdRoute
  RoadmapsNewRoute: typeof RoadmapsNewRoute
  RoadmapsIndexRoute: typeof RoadmapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/': {
      id: '/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof RoadmapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/$roadmapId': {
      id: '/roadmaps/$roadmapId'
      path: '/roadmaps/$roadmapId'
      fullPath: '/roadmaps/$roadmapId'
      preLoaderRoute: typeof RoadmapsRoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/new': {
      id: '/roadmaps/new'
      path: '/roadmaps/new'
      fullPath: '/roadmaps/new'
      preLoaderRoute: typeof RoadmapsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  RoadmapsRoadmapIdRoute: RoadmapsRoadmapIdRoute,
  RoadmapsNewRoute: RoadmapsNewRoute,
  RoadmapsIndexRoute: RoadmapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
